### ISSUE TITLE
Vector2D does not contain a definition for .Dot() and .Abs()

### ISSUE THREAD

**Issue by joreg** [ThomasJackDalby/svg2gcode#2]
hey @ThomasJackDalby thanks for your work on this.

the compiler complains about this for ArcToCommand.cs:37. it looks like you maybe simply forgot to push this?

**Comment by ThomasJackDalby** [comment]
Hey, you're completely right, I had a few uncommit changes locally. Just pushed them, hopefully that helps! Thanks for the heads up 👍

**Comment by joreg** [comment]
perfect, thanks!
